name: Issue
on:
  issues:
    types: [opened, edited]
jobs:
  listen:
    runs-on: ubuntu-latest
    steps:
      - name: Copy code
        use: actions/checkout@v3
      - name: Install nodejs
        use: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: display details
        run: exho "${{ github }}"
